version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todoapp
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Your Backend App
  app:
    image: deepnav/backend-app-v1:latest
    container_name: backend-app
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/todoapp
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

volumes:
  postgres-data:
